# Generated by Django 5.2.4 on 2025-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventbooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_response', 'Meeting Response'), ('announcement', 'Announcement'), ('booking_cancellation', 'Booking Cancellation'), ('booking_update', 'Booking Update')], max_length=50),
        ),
    ]
